[package]
name = "twitter-bot"
version = "0.1.0"
authors = ["JGeiser9 <jake@urkel.com>"]
edition = "2018"

[dependencies]
failure = "0.1.8"
failure_derive = "0.1.8"
oauth-client = "0.4.0"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.56"
twitter-api = "*"
